---
variables:
  hello: world

stages:
  - build
  - test

build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
     - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --no-push

test:
  image: docker.io/library/busybox:latest
  services:
    - docker.io/library/redis:latest
  script:
    - echo "hello $hello"
