---
name: CI on push
on:
  push:
    branches:
      - main
      - master
  pull_request: {}
jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       go: [ '1.21', '1.22' ]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/cache@v4
  #       with:
  #         path: ~/.cache/golangci-lint
  #         key: golangci-lint
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ matrix.go }}
  #     - run: make lint
  #     - run: make test
  build:
    runs-on: ubuntu-latest
    #needs:
    #  - check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Fetch target branch and merge
      #   run: |
      #     TARGET="${{ github.base_ref }}"
      #     echo $TARGET
      #     git fetch origin $TARGET:$TARGET
      #     git merge origin/$TARGET
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make
      - uses: actions/cache@v4
        with:
           path: ${{github.workspace}}/cache
           key: kaniko-cache
      - uses: docker://gcr.io/kaniko-project/warmer:latest
        with:
          args: --cache-dir=${{github.workspace}}/cache --dockerfile=Dockerfile
          working-directory: ${{github.workspace}}
      - uses: docker://gcr.io/kaniko-project/executor:latest
        with:
          args: --cache-dir=${{github.workspace}}/cache --context=${{github.workspace}} --dockerfile=Dockerfile --reproducible --no-push --tarPath ${{github.workspace}}/image.tar
