---
name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request: {}
jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       go: [ '1.21', '1.22' ]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/cache@v4
  #       with:
  #         path: ~/.cache/golangci-lint
  #         key: golangci-lint
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ matrix.go }}
  #     - run: make lint
  #     - run: make test
  build:
    runs-on: ubuntu-latest
    #needs:
    #  - check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Fetch target branch and merge
      #   run: |
      #     TARGET="${{ github.base_ref }}"
      #     echo $TARGET
      #     git fetch origin $TARGET:$TARGET
      #     git merge origin/$TARGET
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version-file: go.mod
      # - run: make
      # - uses: actions/cache@v4
      #   with:
      #     path: ${{github.workspace}}/cache
      #     key: kaniko-cache
      # - uses: docker://gcr.io/kaniko-project/warmer:latest
      #   with:
      #     args: --cache-dir=${{github.workspace}}/cache --dockerfile=Dockerfile
      #     working-directory: ${{github.workspace}}
      # - uses: docker://gcr.io/kaniko-project/executor:latest
      #   with:
      #     args: --context=/github/workspace --dockerfile=/github/workspace/Dockerfile --no-push --tarPath=/github/workspace/image.tar
      # - run: docker run --rm -v ~/cache:/cache -v ${{github.workspace}}:/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/cache -d /workspace/Dockerfile
      # - run: docker run --rm -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest --no-push
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ghcr.io/blame2020/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: github.event_name == 'push'
